# These are supported funding model platforms

github: [petersirka, tomee03, PatchwerkQWER]
patreon: totaljs
open_collective: totaljsplatform
ko_fi: totaljs
custom: ['https://www.totaljs.com/support/']
